### ISSUE TITLE
do not create certificates if the files already exist

### ISSUE THREAD

**Issue by karimra** [srl-wim/container-lab#114]
Currently certificates are generated regardless of whether (SRL) config files exist or not.
In case of subsequent deploys of the same lab (with existing config), this results on SRL certificates not being verifiable using the new rootCA file.

the proposal is to add a few features to be able to avoid this situation.
- if a rootCA file exists (and nodes certificates? and config files?) ==> skip the certificates generation step altogether
- add a flag to destroy command to delete lab files (certificates and config)
- add a flag to deploy command to delete lab files if they exist

**Comment by hellt** [comment]
points 2 and 3 are implemented via `destroy --cleanup` and `deploy --reconfigure` accordingly.

**Comment by hellt** [comment]
the last part is delivered via #338 
if rootCA exists and node cert/key exist the certificate generation will be skipped
