### ISSUE TITLE
add a flag to skip certs generation

### ISSUE THREAD

**Issue by hellt** [srl-wim/container-lab#172]
For the kinds where certs can be locally generated or not needed it might be nice to have a config option to skip cert generation for the global/kind/node case

**Comment by karimra** [comment]
if certificates are skipped, what should the user expect in the SRL tls profile config?
* a dummy profile with certificate and key set to "changeme" ?
* no tls profile configured? in this case we will need to skip the gnmi server config as well

**Comment by hellt** [comment]
I'm in favor of having certificates data generated for a dummy node and
populated in the config when certs generation is skipped.


Then even with --skip-certs there will be certificates data that is
technically correct and gnmic can use it with --skip-verify to execute RPCs

**Comment by karimra** [comment]
What's the advantage of a dummy certificate over the current functionality?
Currently, gnmi rpc can be executed both with and without tls certificate verification

**Comment by hellt** [comment]
in #337 and #338 this issue has been addressed
with these changes the certificates are generated only for SRL nodes (since it is the only kind who leverages them today). The rootCA will be skipped if no SRL nodes are present in the topo file.
If certificates are present (root CA and/or node certs), they will be reused during the deploy
