### ISSUE TITLE
make bridge mtu configurable and default to 1450 instead of 1500

### ISSUE THREAD

**Issue by hellt** [srl-wim/container-lab#196]
to allow for zer-touch cloud based installations of containerlab the proposal is to enforce mtu for `clab` bridge to be 1450

**Comment by steiler** [comment]
the subshelling branch contains a struct and functionality for setting the MTU. This would then just need to be further exposed towards the input file.

**Comment by hellt** [comment]
@steiler I think your PR introduces ability to set the MTU on the non-management links. The links that we create either for p2p connectivity, or point-to-bridge connection.

Here I am talking about the management network mtu, that docker creates to attach management interfaces of the containters
