### ISSUE TITLE
add a `redeploy` command (make --reconfigure to cause redeployment)

### ISSUE THREAD

**Issue by hellt** [srl-wim/container-lab#210]
quite often during a lab build process we need to redeploy a lab. 

`redeploy` command is a sequence of `destroy_cleanup+deploy` commands

**Comment by karimra** [comment]
why not add a flag to deploy cmd, just like `--reconfigure`, maybe a `--cleanup`

**Comment by hellt** [comment]
discussed internally and the proposal changed to enhance the existing `deploy --reconfigure` flag to first run a `destroy` command that will ensure the existing lab is destroyed first
