### ISSUE TITLE
Wrong SRL leaf node type on closXX topologies

### ISSUE THREAD

**Issue by sacckth** [srl-wim/container-lab#287]
Hello, couldn't help but notice that model ixrd1 for SRL in CLOS topology examples and documentation is misused.
Leaf models supported by Nokia with all features are either IXRD2 (leaf) or IXRD3 (leaf/spine). Out of completeness D1 models are aimed for Out Of Band type of services and may not come with all features required for a leaf switch.

**Comment by hellt** [comment]
thanks @sacckth 
this issue has been addressed in #288 
I used ixrd2 everywhere where ixrd1 was mentioned. Will that suffice?

**Comment by sacckth** [comment]
Yes, that should do it. Thanks @hellt !
