### ISSUE TITLE
[enhancement] containerlab version requires right elevation

### ISSUE THREAD

**Issue by azyablov** [srl-wim/container-lab#339]
Minor issue, but issue sudo to check version installed could be a potential security concern for some environments.

```
[admin@dct0 clab]$ containerlab version
containerlab requires sudo privileges to run!
```

**Comment by hellt** [comment]
Hey @azyablov, thanks for taking time raising an issue

version (and a few other cmds) will not require sudo in the next release, but deploy/destroy/inspect commands will require sudo privileges still.
