### ISSUE TITLE
incorrect node type should not panic but log.fatal

### ISSUE THREAD

**Issue by hellt** [srl-wim/container-lab#48]
Hi @steiler 
I think its better to use log.Fatalf rather than panic here 

https://github.com/srl-wim/container-lab/blob/5b87055a5f0bf7a44f765593c5ac0fe1e838cc40/clab/config.go#L294

and would also be lovely to print out the incorrect type name for a user to see where did they typo'ed

**Comment by steiler** [comment]
Thanks @hellt for the comment. 
There are many other panics in the clab/file.go which I simply copied back then. Should they also be refactored? 

Your comments are resolved via #51 in 8de151e8cb72063bb9849ada2fb1ee13a15a2073
