### ISSUE TITLE
`config` key must not be present for kind definition?

### ISSUE THREAD

**Issue by hellt** [srl-wim/container-lab#76]
a config directive points to a precise config file that can be used as-is with a certain node
making config available for `kinds` does not make sense, since every instance of a kind should have its own config?

**Comment by karimra** [comment]
I think it could make sense for a generic config. But that node won't have auto generated certificates configured. 

But the config parameter is ignored right now (for both kind and dut) in favor of the config template. This was done to set different certificates for each node. 
The only case where a config is not generated is when a config file exists on the path to be mounted (recreating an old lab where config was already generated and maybe modified) 

We can revisit and not generate config from template if the config param is specified. Instead the config file specified for that node will be copied to the mount location, and the certificates generation is skipped for that node.

**Comment by hellt** [comment]
Yes, its worth discussing this
Maybe that should be a template that will undergo the same `generateConfig` func?

**Comment by karimra** [comment]
ok makes sense, let's keep the config parameter then. 
It can be used to pass a template or a plain text file. 
it then makes sense to have it under kind as well

**Comment by hellt** [comment]
closed via #127
