### ISSUE TITLE
add a container label which will point to the topology file this container was created from

### ISSUE THREAD

**Issue by hellt** [srl-wim/container-lab#82]
Currently its hard to understand which topo file was used to spin up containers after the creation.

I propose we add a label that will point to the abs file path of the topology that was used to create those nodes.

What I think also can be added is the `containerlab inspect` command which can be used without arguments and will output all containers from all the labs with topo file paths. This will make it possible to see which labs were deployed on the host and how to destroy them

**Comment by karimra** [comment]
Agree, but we should copy the original topology file during deploy and store it under the lab directory ( can be a hidden file ), the original file could be modified by the user in the future.
Labels can be added for both files, but I think pointing to the copy is enough.

Agree for inspect command as well, should be able to display all labs. this can be done by filtering for label=containerlab

The destroy command doesn't really need the topology file, all we need right now is the prefix:
- get all containers with label=containerlab=lab-$prefix
- delete those containers
- delete network NS with the containers names
- delete the symlinks

The way destroy is done right now is not correct, it loops through the links and deletes the nodes referenced by the links.
Two issues with that:
1- NS could be deleted multiple times, results in error messages
2- Nodes without links do not get their NS symlink cleaned up.

The only missing behavior is deleting the interfaces added to a bridge node, which is also not being done right now.
This can be addressed once the naming of the interface is agreed upon.
