### ISSUE TITLE
Common Label in example topologies

### ISSUE THREAD

**Issue by steiler** [srl-wim/container-lab#98]
I propose using a more general label in the example topologies.
Right now we are using:
```
  kind_defaults:
    srl:
      image: srlinux:20.6.1-286
```
I propose to change this to either ´srlinux:latest´... or `srlinux:containerlab`, which would decouple the config from the actual GA release.

**Comment by hellt** [comment]
good suggestion, I will use `:latest` in the examples I create in #96

**Comment by steiler** [comment]
We should then extend the doc, such that the tag is to be set on setup, since on image import just the specific version tag is available.
```
docker tag srlinux:<VERSION-TAG> srlinux:latest
```

**Comment by hellt** [comment]
@steiler I have added the note and fixed the templates in https://github.com/srl-wim/container-lab/pull/96/commits/18b81c8698664d14e1ed8d3c6bf2e4f03599a4bd

What do you think?

**Comment by steiler** [comment]
Yes, that looks good to me.
We should do the same with the already existing topologies in the lab-examples folder. Would you please incorporate that as part of your commit?

**Comment by hellt** [comment]
my goal is to discontinue the old lab examples as part of that PR.
Which examples you are using from the old selection?

**Comment by steiler** [comment]
Opportunistically I've been simply utilising the wan-topo.
But I don't have strong feelings about that. Lets get rid of it.

**Comment by hellt** [comment]
but its interesting to see what features of wan-topo I need to replicate
I see that wan-topo had some lags between nodes, that was the idea, @henderiw?

Ideally I would like to know if we think about SRL in WAN today, what is the minimum viable topology would be useful to have? I can reuse wan-topo example, but now would be a good time to ask for changes in that topo
